version: "3.5"
services:
  superset-webserver:
    image: mpolatcan/superset:0.37.0-python3.7
    container_name: superset-webserver
    hostname: superset-webserver
    env_file:
      - prod-redis.env
    environment:
      SUPERSET_DAEMONS: |
        init
        webserver
        flower
    ports:
      - 8088:8088
      - 5555:5555

  superset-worker:
    image: mpolatcan/superset:0.37.0-python3.7
    env_file:
      - prod-redis.env
    environment:
      SUPERSET_DAEMONS: |
        worker

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379