version: "3.5"
services:
  superset:
    image: mpolatcan/superset:dev
    container_name: superset
    hostname: superset
    environment:
      - METADATA_DB_TYPE=postgresql
      - METADATA_DB_HOST=postgres
      - METADATA_DB_PORT=5432
      - METADATA_DB_USERNAME=admin
      - METADATA_DB_PASSWORD=admin
      - METADATA_DB_DATABASE=admin
      - SUPERSET_MAX_RETRY_TIMES=-1
      - FEATURE_FLAG_SIP_38_VIZ_REARCHITECTURE=True
      - FEATURE_FLAG_LIST_VIEWS_NEW_UI=True
      - LOAD_EXAMPLES=true
    ports:
      - 8088:8088

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
