version: "3.5"
services:
  superset-webserver:
    image: mpolatcan/superset:dev
    container_name: superset-webserver
    hostname: superset-webserver
    environment:
      SUPERSET_DAEMONS: |
        init
        webserver
      SUPERSET_DEPLOY_MODE: "local"
      METADATA_DB_TYPE: "postgresql"
      METADATA_DB_HOST: "postgres"
      METADATA_DB_PORT: "5432"
      METADATA_DB_USERNAME: "admin"
      METADATA_DB_PASSWORD: "admin"
      METADATA_DB_DATABASE: "admin"
      CELERY_BROKER_TYPE: "redis"
      CELERY_BROKER_HOST: "redis"
      CELERY_BROKER_PORT: "6379"
      CELERY_BROKER_DATABASE: "0"
      RESULTS_BACKEND_TYPE: "redis"
      RESULTS_BACKEND_REDIS_HOST: "redis"
      RESULTS_BACKEND_REDIS_DB: "0"
      SUPERSET_MAX_RETRY_TIMES: "-1"
      LOAD_EXAMPLES: "true"
    ports:
      - 8088:8088

  superset-worker:
    image: mpolatcan/superset:dev
    environment:
      SUPERSET_DAEMONS: |
        worker
      SUPERSET_MAX_RETRY_TIMES: "-1"
      METADATA_DB_TYPE: "postgresql"
      METADATA_DB_HOST: "postgres"
      METADATA_DB_PORT: "5432"
      METADATA_DB_USERNAME: "admin"
      METADATA_DB_PASSWORD: "admin"
      METADATA_DB_DATABASE: "admin"
      CELERY_BROKER_TYPE: "redis"
      CELERY_BROKER_HOST: "redis"
      CELERY_BROKER_PORT: "6379"
      CELERY_BROKER_DATABASE: "0"
      RESULTS_BACKEND_TYPE: "redis"
      RESULTS_BACKEND_REDIS_HOST: "redis"
      RESULTS_BACKEND_REDIS_DB: "0"

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379