version: "3.5"
services:
  superset:
    image: mpolatcan/superset
    container_name: superset
    hostname: superset
    environment:
      - METADATA_DB_TYPE=postgresql
      - METADATA_DB_HOST=postgres
      #- METADATA_DB_PORT=5432
      - SUPERSET_MAX_RETRY_TIMES=-1
    ports:
      - 8088:8088

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
