version: "3.5"
services:
  superset:
    image: mpolatcan/superset
    container_name: superset
    hostname: superset
    entrypoint: sleep infinity
    environment:
      - CACHE_CONFIG_CACHE_TYPE=simple
      - TABLE_NAMES_CACHE_CONFIG_CACHE_TYPE=simple
      - THUMBNAIL_CACHE_CONFIG_CACHE_TYPE=simple
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://admin:admin@postgres:5432/admin
      - SQLALCHEMY_EXAMPLES_URI=postgresql+psycopg2://admin:admin@postgres:5432/admin
      - LOAD_EXAMPLES=true
    ports:
      - 8088:8088
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
