name: superset-docker

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-lastest
  steps:
    - uses: actions/checkout@v1
    - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - run: docker build -q -t ${{secrets.DOCKER_USERNAME}}/superset src/
    - run: docker push ${{secrets.DOCKER_USERNAME}}/superset
    - run: docker rmi ${{secrets.DOCKER_USERNAME}}/superset